### ISSUE TITLE
学习一下，请问你用来训练的数据是人工一个个做出来的吗？

### ISSUE THREAD

**Issue by magicknight** [skyduy/CNN_keras#1]
还是超星支持给了数据? 6000个训练数据耗了多少时间啊。

**Comment by skyduy** [comment]
@magicknight 自己一个个敲的。。。  训练话的时间倒不多，好像是半个小时，N卡型号忘记了。

**Comment by yangyuhui** [comment]
训练之后，识别单张验证码耗时多久

（还有弱弱问一句，能在windows下开发吗）

**Comment by skyduy** [comment]
@yangyuhui
单张识别时间我没计算，0.1s左右吧估计……
唔……我就是在windows开发的，直接用的Anaconda，另装的cuda(如果N卡支持)和Theano, Keras.

**Comment by ithjz** [comment]
Win7 can not install this PIP install Graph,     What kind of environment do you install ？ cento7 or mac?

**Comment by ithjz** [comment]
I use the Tensorflow version of the CPU

**Comment by skyduy** [comment]
@ithjz 
I used theano as backend of keras before.

If you use windows, I recommend Anaconda as environment.
