### ISSUE TITLE
About dataset for trainning

### ISSUE THREAD

**Issue by manhcuong-nguyen** [skyduy/CNN_keras#13]
Hi, can you tell me about the dataset ? How is it organized ? Thank you ?

**Comment by skyduy** [comment]
Please read README.md.

**Comment by manhcuong-nguyen** [comment]
Thank for your help ! I want to use your network to recognize some image like this one. Do you think it's Ok ?
![test-lieu24](https://user-images.githubusercontent.com/22500503/36546517-ec31e41a-17eb-11e8-906d-fe489e1cfc72.png)

**Comment by manhcuong-nguyen** [comment]
And the size of image is not fix.

**Comment by skyduy** [comment]
If the single letter's size is fixed and it's shape is regular, find the threshold and cut them into single letter, then recognize them separately just using sklearn.

**Comment by manhcuong-nguyen** [comment]
Thank you for your reply ! but the size is not fixed and the shape isn't regular :(

**Comment by oneoy** [comment]
请问这个项目基于Windows还是Linux?

**Comment by LiuChuang1992** [comment]
linux

**Comment by oneoy** [comment]
有没有Windows的文件项目  顺便问下你的QQ多少 或者邮箱  有很多问题想请教您

**Comment by LiuChuang1992** [comment]
850431942 windows下面你安装好环境也是一样的。

**Comment by oneoy** [comment]
OK  我试试

**Comment by oneoy** [comment]
我这有C#写的验证码识别  但是识别率太低了 而且没法批量训练
