### ISSUE TITLE
is possible break this?

### ISSUE THREAD

**Issue by letarg0** [skyduy/CNN_keras#15]
https://github.com/aero2a/kape-
This is public captcha for Aero2. Very complicated and many digits.
Is possible generate data using this library https://github.com/letarg0/obrazy

Is possible?

**Comment by skyduy** [comment]
Sorry for the late reply.
Actually it's impossible to generate the **same** type of captcha if you don't know the code used to generate that captcha.
But you can make some small changes on your collected samples to enlarge your training data.
