### ISSUE TITLE
==问下这种怎么分割

### ISSUE THREAD

**Issue by Octoberr** [skyduy/CNN_keras#17]
感谢分享
![2AXS_1554979638637006](https://user-images.githubusercontent.com/17826158/56189073-a948ff00-6059-11e9-99b4-e0f16bccdba5.png)

**Comment by skyduy** [comment]
https://github.com/skyduy/CNN_keras/tree/pytorch

这个分支下的解决方案不需要分割验证码

**Comment by Octoberr** [comment]
但是这种端到端的训练方式会需要大量的样本，否则的话效果会很不好，啊现在卡在了训练样本这，大佬可否给个模仿生成这种验证码的方式呢

**Comment by Octoberr** [comment]
思路，不好意思打错了

**Comment by skyduy** [comment]
可以尝试对图片进行抖动等方案进行样本扩充，模仿生成的不能保证来自同一分布

**Comment by Octoberr** [comment]
额--、，以前做算法的没怎么设计过图片处理，简单点说呢

**Comment by LiuChuang1992** [comment]
图片处理你是指哪方面，图片加噪声还是倾斜




------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 下午3:36
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




额--、，以前做算法的没怎么设计过图片处理，简单点说呢

**Comment by Octoberr** [comment]
就是这个英文字符是怎么能够这么弯曲的，我也用PIL试过，但是完全做不到这种

**Comment by LiuChuang1992** [comment]
弯曲？？你说的是字体倾斜吗，Keras有个模块是专门处理这个的




------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午3:41
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




就是这个英文字符是怎么能够这么弯曲的，我也用PIL试过，但是完全做不到这种

**Comment by Octoberr** [comment]
有吗？我没用过keras，给个方向我去查查呢

**Comment by Octoberr** [comment]
大概叫什么？

**Comment by LiuChuang1992** [comment]
Keras中文文档，具体那个包我忘啦。我现在不做这方面好长时间啦




------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午3:46
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




大概叫什么？

**Comment by LiuChuang1992** [comment]
样本你是可以自动生成样本的，你自己随机生成数字和字母，然后生成图片，图片的可以加各种噪声，例如高斯噪声，白噪声。。。，opencv这个库就能给你解决，数据问题很好解决。




------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午3:46
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




大概叫什么？

**Comment by Octoberr** [comment]
额，你这么一说伤到我了

**Comment by LiuChuang1992** [comment]
你可能以前没接触过图像处理的知识，你如果循环神经网络框架用的tf、pytorch的话，你可以用python调opencv的方法。



------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午4:07
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




额，你这么一说伤到我了

**Comment by skyduy** [comment]
@Octoberr opencv的使用样例可以去这个repo看： https://github.com/skyduy/CAPTCHA_generator

**Comment by LiuChuang1992** [comment]
可以的，你只要能随机生成你想要的就行




------------------ 原始邮件 ------------------
发件人: "YuJun"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午4:22
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




@Octoberr opencv的使用样例可以去这个repo看： https://github.com/skyduy/CAPTCHA_generator

**Comment by Octoberr** [comment]
--我就是查captcha generator，然后从你那里过来的，我用的是tf写的cnn，就是leecun的那个识别手写数字字的例子，然后我改了输入和输出，让他能够识别4位的字符，我用自己生成的验证码去训练，但是结果是没法识别我给出的那张图片的，我就觉得是特征不太准确，因为图片中的字母扭曲的很严重，而简单的字体倾斜好像达不到效果

**Comment by LiuChuang1992** [comment]
你用cnn+lstm试一试，cnn的识别准确率不是很高，尤其在有噪声，变形的情况下



------------------ 原始邮件 ------------------
发件人: "linxi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午4:29
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>; 
抄送: "爱你"<850431942@qq.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [skyduy/CNN_keras] ==问下这种怎么分割 (#17)




--我就是查captcha generator，然后从你那里过来的，我用的是tf写的cnn，就是leecun的那个识别手写数字字的例子，然后我改了输入和输出，让他能够识别4位的字符，我用自己生成的验证码去训练，但是结果是没法识别我给出的那张图片的，我就觉得是特征不太准确，因为图片中的字母扭曲的很严重，而简单的字体倾斜好像达不到效果

**Comment by Octoberr** [comment]
==重写了下代码，加了BLSTM，收敛变得好慢，讲真不是很懂这原理，这个数学公式也太复杂了吧

**Comment by Octoberr** [comment]
感谢，准确率提高不少
