### ISSUE TITLE
shape problem 

### ISSUE THREAD

**Issue by Shavell** [skyduy/CNN_keras#18]
Hi, 

..../Desktop/captcha/core/train.py
Using TensorFlow backend.
... loading data
total letters: 49990
Traceback (most recent call last):
  File "C:/Users/..../Desktop/captcha/core/train.py", line 89, in <module>
    weight_folder=r'../models'
  File "C:/Users/..../Desktop/captcha/core/train.py", line 52, in train
    x_train, y_train, x_test, y_test = prepare_data(pic_folder)
  File "C:/Users/..../Desktop/captcha/core/train.py", line 25, in prepare_data
    data, label = load_data(folder)
  File "C:\Users\....\Desktop\captcha\core\utils.py", line 34, in load_data
    data[index*5+sub_index, :, :, :] = img / 255
ValueError: could not broadcast input array from shape (40,29,3) into shape (40,40,3)

why i get shape error that's any dataset

**Comment by LiuChuang1992** [comment]
your data is not fit, you should check your data

------------------ 原始邮件 ------------------
发件人: "Shavell"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 凌晨3:23
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [skyduy/CNN_keras] shape problem  (#18)




Hi,
 
..../Desktop/captcha/core/train.py
 Using TensorFlow backend.
 ... loading data
 total letters: 49990
 Traceback (most recent call last):
 File "C:/Users/..../Desktop/captcha/core/train.py", line 89, in 
 weight_folder=r'../models'
 File "C:/Users/..../Desktop/captcha/core/train.py", line 52, in train
 x_train, y_train, x_test, y_test = prepare_data(pic_folder)
 File "C:/Users/..../Desktop/captcha/core/train.py", line 25, in prepare_data
 data, label = load_data(folder)
 File "C:\Users....\Desktop\captcha\core\utils.py", line 34, in load_data
 data[index*5+sub_index, :, :, :] = img / 255
 ValueError: could not broadcast input array from shape (40,29,3) into shape (40,40,3)
 
why i get shape error that's any dataset

**Comment by Shavell** [comment]
ty for response but if i want to use with under samples/ folder (from git) images, thats always return this exception. 


my samples:

![1a6cy](https://user-images.githubusercontent.com/12944270/59586177-f34a7180-90ea-11e9-97fe-53d539368fb6.jpg)
![1acyh](https://user-images.githubusercontent.com/12944270/59586178-f34a7180-90ea-11e9-8362-3476eb8256a8.jpg)
![1ad1p](https://user-images.githubusercontent.com/12944270/59586179-f3e30800-90ea-11e9-857d-426f46e95f03.jpg)

**Comment by skyduy** [comment]
You should custom [preprocessing model](https://github.com/skyduy/CNN_keras/blob/master/core/preprocess.py) for specific CAPTCHA  or use branch [pytorch](https://github.com/skyduy/CNN_keras/tree/pytorch) which does not need preprocessing but may need modify some CNN paramer for your sample.

**Comment by LiuChuang1992** [comment]
Think for your advice



------------------ 原始邮件 ------------------
发件人: "YuJun"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 下午5:10
收件人: "skyduy/CNN_keras"<CNN_keras@noreply.github.com>;
抄送: "爱你"<850431942@qq.COM>;"Comment"<comment@noreply.github.com>;
主题: Re: [skyduy/CNN_keras] shape problem  (#18)




You should custom preprocessing model for specific CAPTCHA  or use branch pytorch which does not need preprocessing but may need modify some CNN paramer for your sample.

**Comment by Shavell** [comment]
ty for interest

**Comment by Shavell** [comment]
@LiuChuang1992 Hi,

can u explain this method?  thats parameters are what does it mean? s, e, center(why center?), 8300 (but why) etc.


[preprocess.py](https://github.com/skyduy/CNN_keras/blob/master/core/preprocess.py)
`
def gen_sub_img(raw_img):
    gray_img = cv2.cvtColor(raw_img, cv2.COLOR_BGR2GRAY)

    s, e = 0, gray_img.shape[1]
    value = np.sum(gray_img, axis=0)
    for i, v in enumerate(value):
        if v <= 8300:
            s = i
            break
    for i, v in enumerate(value[::-1]):
        if v <= 8200:
            e = e - i
            break

    centers = [((2 * i + 1) * e + (9 - 2 * i) * s) // 10 for i in range(5)]
    for sub_index, center in enumerate(centers):
        a = center - 20
        b = center + 21
        if a < 0:
            a = 0
            b = a + 40
        if b > 150:
            b = 150
            a = b - 40
        yield raw_img[:, a:b, :]
`

**Comment by skyduy** [comment]
@Shavell 
The function of preprocessing.py is to split the whole picture into five parts, each part is a single letter.

But the method is different for different CAPTCHA, so it's okay if you cannot read this script.

You can find a better way to split your CAPTCHA.
