### ISSUE TITLE
how to run it？

### ISSUE THREAD

**Issue by TopSpoofer** [skyduy/CNN_keras#2]
what it's dependency

**Comment by skyduy** [comment]
@TopSpoofer
Numpy, Scipy, Skleran, Keras is the primary dependency. The backend of Keras can be TensorFlow or Theano where you can find in docs of Keras. You can get other dependency while running it. 

The folder 'core' is the entrance of this project.

**Comment by lxj0276** [comment]
你这个版本还记得吗，theano，keras的版本是多少，我现在运行出错

**Comment by skyduy** [comment]
@lxj0276 
我是windows下的anaconda, theno版本是0.9.0dev1.dev-RELEASE, keras版本是1.0.3。
