### ISSUE TITLE
1

### ISSUE THREAD

**Issue by humorist6** [skyduy/CNN_keras#21]
为什么不把训练数据集也打包上传呀

**Comment by skyduy** [comment]
https://docs.github.com/en/github/managing-large-files/working-with-large-files/conditions-for-large-files#warning-for-files-larger-than-50-mb

**Comment by skyduy** [comment]
> 为什么不把训练数据集也打包上传呀

https://docs.github.com/en/github/managing-large-files/working-with-large-files/conditions-for-large-files#warning-for-files-larger-than-50-mb

**Comment by humorist6** [comment]
因为刚学深度学习，所以想找个项目复现
