### ISSUE TITLE
cannot import name asc_chr

### ISSUE THREAD

**Issue by steermomo** [skyduy/CNN_keras#3]
When I run predict_1.py after I have install the utils through pip, but still this problem.

```
Traceback (most recent call last):
  File "predict_2.py", line 14, in <module>
    from utils import asc_chr
ImportError: cannot import name asc_chr
```

and I didn't find anything about asc_chr in [utils source code](https://github.com/WoLpH/python-utils).
what's wrong with my solution?

**Comment by steermomo** [comment]
![](http://7xlkdd.com1.z0.glb.clouddn.com/python_utils.png)

**Comment by skyduy** [comment]
@hakale
The 'utils' is the script file in the folder 'CNN_keras', not the package of Python. 
This problem occured becasue your PYTHON_PATH doesn't contain your project's root folder (Here it's CNN_keras) or makes the priority of package wrong.
You can just copy the function 'asc_chr' in file 'CNN_keras/utils' to your shell 'ipython' and call it directly.

**Comment by steermomo** [comment]
@skyduy  thanks
