### ISSUE TITLE
你好，能说下你分割图片的思路吗？

### ISSUE THREAD

**Issue by BigUncle** [skyduy/CNN_keras#6]
你好，能说下你分割图片的思路吗？
我手上自己在写的一个程序卡在分割上。
谢谢。
![6p5p](https://cloud.githubusercontent.com/assets/9360607/20641753/d11acc80-b439-11e6-91ce-a04974a76718.gif)

**Comment by skyduy** [comment]
我当时是二值化之后，投影到X轴，可视化，然后结合图片手动找阈值，然后确定图片中心位置。你这种图片的话，应该也可以考虑投影并找阈值。
