### ISSUE TITLE
centers = [((2*i+1)*end+(9-2*i)*begin)/10 for i in range(4)]分割语句中的这个是什么意思？多谢

### ISSUE THREAD

**Issue by xdkaka** [skyduy/CNN_keras#7]
centers = [((2*i+1)*end+(9-2*i)*begin)/10 for i in range(5)]
分割语句中的这个，就是寻找5个中间点进行分割然后出来的这个进行计算是什么意思？多谢

**Comment by skyduy** [comment]
@xdkaka 
其中begin和end变量是图片的左右边界，这句代码功能就是根据左右边界像素位置将图片平均分为5份，并返回五份的中心点横坐标。
((2*i+1)end+(9-2i)*begin)/10 是化简后的结果。  i代表第几份（0，1，2，3，4）
